"""Poisson dataset: analytical multi-frequency source/solution pairs on a structured grid.

The source ``f`` and the analytical solution ``u`` are produced by TensorMesh's
``PoissonMultiFrequency`` (``r=-0.5``). Each sample is exposed both as an image-shaped
grid (for the FNO input/target) and as the flat node vector (for the FEM losses, which
operate on node values via :class:`PoissonProblem`).
"""

from typing import List, Optional

import torch
from torch.utils.data import Dataset

from tensormesh.dataset import PoissonMultiFrequency

from .meshing import structured_quad_mesh, node_to_grid
from .physics import PoissonProblem

__all__ = ["PoissonDataset", "create_datasets"]


class PoissonDataset(Dataset):
    """Dataset of (source, analytical-solution) pairs on a structured quad grid.

    Each item is ``((f_grid [1,H,W], grid_size, f_node [N], u_node [N]), u_grid [H,W])``,
    where ``H = ny``, ``W = nx`` and ``N = nx*ny``. The grid form feeds the FNO; the node
    form feeds the FEM-based losses.
    """

    def __init__(
        self,
        num_samples: int = 1000,
        K: int = 4,
        seed: int = 42,
        grid_resolution: int = 64,
        mesh=None,
        problem: Optional[PoissonProblem] = None,
        all_data: Optional[dict] = None,
        indices: Optional[List[int]] = None,
    ):
        super().__init__()
        self.K = K
        self.grid_resolution = grid_resolution
        self.grid_size = (grid_resolution, grid_resolution)   # (nx, ny)

        if all_data is not None:
            # Reuse mesh/problem/fields generated by a sibling split.
            self.mesh = mesh
            self.problem = problem
            if indices is not None:
                self.fs = [all_data["fs"][i] for i in indices]
                self.us = [all_data["us"][i] for i in indices]
                self.l_a = all_data["l_a"][indices]
            else:
                self.fs = all_data["fs"]
                self.us = all_data["us"]
                self.l_a = all_data["l_a"]
            self._all_data = all_data
        else:
            torch.manual_seed(seed)
            self.mesh = structured_quad_mesh(nx=grid_resolution, ny=grid_resolution)
            self.problem = PoissonProblem(self.mesh)

            # Random K x K coefficients in [-1, 1]
            self.l_a = (torch.rand(num_samples, K, K) * 2 - 1)
            equation = PoissonMultiFrequency(a=self.l_a, r=-0.5)
            points = self.mesh.points                              # [N, 2], float64
            all_fs = equation.source_term(points, domain="rectangle").float()   # [num, N]
            all_us = equation.solution(points).float()                          # [num, N]

            self.fs = [all_fs[i] for i in range(num_samples)]
            self.us = [all_us[i] for i in range(num_samples)]
            self._all_data = {"fs": self.fs, "us": self.us, "l_a": self.l_a}

    def __len__(self):
        return len(self.fs)

    def __getitem__(self, idx):
        f = self.fs[idx]                       # [N]
        u = self.us[idx]                       # [N]
        nx, ny = self.grid_size
        f_grid = node_to_grid(f, nx, ny).unsqueeze(0)   # [1, H=ny, W=nx]
        u_grid = node_to_grid(u, nx, ny)                # [H, W]
        return (f_grid, self.grid_size, f, u), u_grid

    def get_shared_resources(self):
        return self.mesh, self.problem, self._all_data


def create_datasets(n_train: int, n_val: int, n_test: int,
                    K: int, grid_resolution: int = 64, seed: int = 42):
    """Build train/val/test splits that share one mesh, one :class:`PoissonProblem`,
    and a single pool of generated samples."""
    total = n_train + (n_val if n_val > 0 else 0) + (n_test if n_test > 0 else 0)
    base = PoissonDataset(num_samples=total, K=K, seed=seed,
                          grid_resolution=grid_resolution)
    mesh, problem, all_data = base.get_shared_resources()

    train_idx = list(range(n_train))
    val_idx = list(range(n_train, n_train + n_val)) if n_val > 0 else train_idx
    if n_test > 0:
        start = n_train + (n_val if n_val > 0 else 0)
        test_idx = list(range(start, start + n_test))
    else:
        test_idx = train_idx

    def _make(indices):
        return PoissonDataset(
            num_samples=total, K=K, seed=seed, grid_resolution=grid_resolution,
            mesh=mesh, problem=problem, all_data=all_data, indices=indices,
        )
    return _make(train_idx), _make(val_idx), _make(test_idx)
